- name: Restart container
  ansible.builtin.command: >-
    docker compose --ansi never --progress plain restart
  args:
    chdir: "{{ limesurvey_docker_path }}"
  changed_when: true
  listen: restart limesurvey
